### ISSUE TITLE
Wenn man eine Shape betritt kommt eine Fehlermeldung "Nicht befugt!"

### ISSUE THREAD

**Issue by SladeGit** [VnX-SolidSnake/VenoX-V#67]

**Comment by VnX-SolidSnake** [comment]
- Bisherige infos von Slade : 

~ Passiert bei Zivi's anscheinend ( auch bei fraktionisten )
~ Reallife Only
~ Bei jeder ColShape

**Comment by VnX-SolidSnake** [comment]
~ Fixed
