### ISSUE TITLE
Todes bug2

### ISSUE THREAD

**Issue by Merthan5446** [VnX-SolidSnake/VenoX-V#80]
Nach dem man respawnt kann man sich nicht mehr bewegen und wenn man mehrmals nach dem tot raus und rein tabt sieht man nur noch den Maus Zeiger und man kann seine Kamera nicht mehr bewegen. https://youtu.be/Rbsw3VrB6z8 und https://youtu.be/WdzoZgmPvvA

(edit das mit dem raus taben ist auch ohne nach dem tot)

**Comment by VnX-SolidSnake** [comment]
(edit das mit dem raus taben ist auch ohne nach dem tot)

~ Da musst du nur ,,alt" drücken damit der Mauszeiger verschwindet.
