### ISSUE TITLE
Auswahl Fenster fehler

### ISSUE THREAD

**Issue by Merthan5446** [VnX-SolidSnake/VenoX-V#82]
Beim ersten mal connecten steht im Auswahl Fenster bei Reallife 0/200 und wenn man dann /hub macht und wieder im Auswahl Fenster ist steht 0/1000 genau so ist es auch bei Tactics am anfang steht 0/40 und nach /hub 0/20.

Wenn man neu auf den Server connectet
Zombie 0/80
7-Towers 0/20(ist nach /hub die gleiche Anzahl)
Tactics 0/40
Race 0/30
Reallife 0/200

Nach /hub
Zombie 0/200
7-Towers 0/20
Tactics 0/20
Race 0/5
Reallife 0/1000

**Comment by VnX-SolidSnake** [comment]
~ Fixed
